name: Deploy ke Cloud Run Otomatis

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kode
        uses: actions/checkout@v4

      - name: Authenticate ke GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and Push to Artifact Registry
        run: |
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet
          gcloud builds submit --tag asia-southeast2-docker.pkg.dev/ets-cloud-matilde/repo-sipelayang/app-image:latest .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy sipelayang-service \
            --image asia-southeast2-docker.pkg.dev/ets-cloud-matilde/repo-sipelayang/app-image:latest \
            --region asia-southeast2 \
            --platform managed \
            --allow-unauthenticated
