name: Deploy ke Cloud Run Otomatis

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ets-cloud-matilde
  SERVICE_NAME: sipelayang-service
  REGION: asia-southeast2
  # Memaksa menggunakan Node 24 agar tidak ada peringatan deprecated
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kode
        uses: actions/checkout@v4

      - name: Authenticate ke GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and Push to Artifact Registry
        run: |
          # Konfigurasi Docker agar bisa push ke Google Artifact Registry
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet

          # Menjalankan build. Jika ada masalah log bucket/VPC, 
          # perintah ini akan tetap mencoba build langsung ke Artifact Registry.
          gcloud builds submit --tag asia-southeast2-docker.pkg.dev/${{ env.PROJECT_ID }}/repo-sipelayang/app-image:latest .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image asia-southeast2-docker.pkg.dev/${{ env.PROJECT_ID }}/repo-sipelayang/app-image:latest \
            --add-cloudsql-instances ${{ env.PROJECT_ID }}:asia-southeast2:db-sipelayang-matilde \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated
